### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by Dreaming-Codes** [RainerStaude/hass-becker-component-plus-pybecker#1]
It would be handy to add the integration to hacs:
https://hacs.xyz/

**Comment by gschmidl** [comment]
Doesn't HACS delete and redownload the entire directory on updates? That would delete your database file as well unless it's moved.

**Comment by Dreaming-Codes** [comment]
> Doesn't HACS delete and redownload the entire directory on updates? That would delete your database file as well unless it's moved.

You're right. It can be solved by putting the db file in a specific folder and then specify the path to that folder in the persistent_directory option

**Comment by gschmidl** [comment]
It's stored right in the pybecker subdirectory.

**Comment by Dreaming-Codes** [comment]
> It's stored right in the pybecker subdirectory.

I don't have any db file inside that directory.

**Comment by gschmidl** [comment]
Marked in green here:

![image](https://user-images.githubusercontent.com/20334/155570942-12e5e5b7-0a4a-470d-8214-6d2a6ffee4d4.png)

**Comment by RainerStaude** [comment]
You make me crazy

1. db file was already stored in config folder IF you choose a different filename. I just changed this to ALWAYS store db file in config folder.
2. loosing your db file is not a big problem. I already added code to restore all configured units in the db file and sync the covers by sending 5 halt codes for each unit. I just found that the num file might be a problem for unit 1. Therefore I removed.

**Comment by RainerStaude** [comment]
I added the description. Hope it works now.

**Comment by Dreaming-Codes** [comment]
> I added the description. Hope it works now.

You also need at least one repository topic.

**Comment by gschmidl** [comment]
It just showed up for me - thank you so much for this, hopefully I wasn't being *too* annoying.

**Comment by RainerStaude** [comment]
@Dreaming-Codes done

**Comment by Dreaming-Codes** [comment]
> @Dreaming-Codes done

Working now

**Comment by Dreaming-Codes** [comment]
> @Dreaming-Codes done

now everything works

**Comment by Dreaming-Codes** [comment]
> @Dreaming-Codes done

now everything works
