### ISSUE TITLE
Not closing completely after pairing stick

### ISSUE THREAD

**Issue by josecarre** [RainerStaude/hass-becker-component-plus-pybecker#10]
Hi, I have paired the USB stick with this HA component, tested it down and up, al good, but now the sun cover doesnt close completely. I dont know why but after pairing the stick as additional controller now it doesnt fully close, like 2 or 3cm, even with HA controls or with original remote, same result :(, any hint? Thanks!

**Comment by RainerStaude** [comment]
I think there is no relationship to HA. If you press open or close, it just send this command to the cover. The same than the remote does.
Has the cover a programmed end position? Maybe the end position has changed for some reason and needs to be re-programmed. Maybe you changed it by mistake during pairing. You will find instructions how to change it in your manual.
Some cover detect their end position by their self. If this is the case, some blocking thing might be the reason.

**Comment by josecarre** [comment]
Thanks for your reply Rainer. Yeah, I know is not related...I see that the crips from ole1986 just send UP DOWN, STOP and PAIR stuff... So maybe I changed something during the pairing, but not sure how, I followed instructions carefully. Anyway I raised an issue here to check if anyone knew any way to fix it. Installer just put the cover and gave me the remote... so I'm not really sure whats's inside and how to re-adjust it... I will call them if I dont find a way to readjust the limits by myself. Thanks anyway and congrats for the HA component, very good work :)

**Comment by RainerStaude** [comment]
Most likely holding the programming button of your remote and the up/down button programs a new end position in up/down direction. This could be happend by mistake. 
Holding the programming button and stop button clears both end position. 
Usually newer products will detect end position automatically. Therefore this might be the right way to overcome you issue.
But as you seems to have a new product with quarantee, ask your installer first.

**Comment by josecarre** [comment]
> 

Thanks Rainer, very helpful! I did a reset with "STOP+Pair" for some seconds till the "2xClank", then it went to manual and I could roll the cover up to the limit, and then programmed the UP & DOWN positions with UP+Pair and DOWN+Pair till "Clank" :), all solved, and USB stick doing it's work as before through HA ;)
