### ISSUE TITLE
How to configure Position sensor

### ISSUE THREAD

**Issue by gamer123** [RainerStaude/hass-becker-component-plus-pybecker#11]
Hi thanks for this great tool,

i try now to get the actuall position of the shutter but i don,t know how to create the sensor for the position. 

Can you may help me with that?

Thanks

julian

**Comment by RainerStaude** [comment]
The cover position is available as attribute "current_position". This is accessible e.g. through automation or templates.
Example template:
"""
{{state_attr("cover.your_cover","current_position")
"""
You can play with templates using Developer Tools -> Template
You can have a look at all your states using Developer Tools -> States
