### ISSUE TITLE
Stick does not receive from remote control

### ISSUE THREAD

**Issue by FrankHdf** [RainerStaude/hass-becker-component-plus-pybecker#14]
Hello, 
I have connected my Becker CentronicPlus USB stick to the HA raspberry. The device path is "/dev/serial/by-id/usb-Becker-Antriebe_GmbH_CentronicPlus_Stick-if00".
I also enabled debug logging but when I press buttons on the original remote EC541-II nothing is logged. 
How can I proceed to locate the problem?
Any help would be greatly appreciated.
Thanks!

**Comment by RainerStaude** [comment]
Sorry, but Centronic Plus is not supported.
See this discussion here:
https://github.com/ole1986/centronic-py/discussions/21
And see this discussion here:
community.home-assistant.io
https://community.home-assistant.io › ...
Integrating Becker Motors in to Hassio - Configuration

**Comment by FrankHdf** [comment]
Oh, I didn't mention this. Thanks for the clarification, I will try to get a non Plus USB stick.
Thanks!

**Comment by RainerStaude** [comment]
But be careful. There is also a repeater available which will not work as well.

**Comment by FrankHdf** [comment]
I hope this is the right one:
https://teso-shop.de/hersteller/becker-antriebe-gmbh/676/usb-funk-stick-centronic-fuer-cc41

Will let you know when it arrives.

**Comment by RainerStaude** [comment]
Looks like the command was received properly. 
Have you restarted HA after adding the remote_id to your configuration.yaml?

**Comment by FrankHdf** [comment]
Yes, several times.

**Comment by FrankHdf** [comment]
Sorry, restarted again, now it works. 
Thanks a lot for this nice integration, I'm really happy to be able to control my covers via HA :-)
