### ISSUE TITLE
NZ/AU 915Mhz Centronic USB Sticks

### ISSUE THREAD

**Issue by timwelchnz** [RainerStaude/hass-becker-component-plus-pybecker#18]
Here in the New Zealand \ Australian region (and possibly others) we use 915Mhz frequency for the Becker Centronic USB stick. 

This, unfortunately, gives it a different device path by id. I have replaced the hard-coded `usb-BECKER-ANTRIEBE_GmbH_CDC_RS232_v125_Centronic-if00` with the device id the 915Mhz stick provides, which is `usb-BECKER-ANTRIEBE_GmbH_CDC_RS232_915_v115_Centronic-if00`. 

With this replacement your component works perfectly but would obviously break on any update.

Would you consider putting in a frequency switch selector into the configuration which could select an alternative frequency and therefore different USB Device ID? 

You could default to the current one so it wouldn't break any current installs but allow the alternative above with a entry in the configuration file. Let me know if you need more information or testing assistance etc.

**Comment by RainerStaude** [comment]
You can change the device path in your configuration.yaml. Have a look at the Readme.

**Comment by timwelchnz** [comment]
Oh, right! I did read this part but it wasn't obvious to me that this was changing the device id used. 

Thanks!
