### ISSUE TITLE
Issue with intermediate positions

### ISSUE THREAD

**Issue by sewie** [RainerStaude/hass-becker-component-plus-pybecker#20]
Hi Rainer,
first of all: great work! :-)

I stumbled across a problem with the intermediate positions:
In the documentation you write:
"If the cover already passed the intermediate position it will close instead. This behaviour is imitated by the Becker integration in Home Assistant. "
The integration works like described, however my covers do not ;-). If I tell my covers to go to an intermediate position, they do so, regardless of at which position they are currently. So when I have a completely closed cover and tell it to go to the "intermediate down" position, it goes there. 

So, can this behaviour be changed in the integration or are there covers out there, that work differently?

**Comment by RainerStaude** [comment]
I don't get it. When the cover is closed and you tell "intermediate down" it will open? What happens when you double tap the down key on your remote?

**Comment by sewie** [comment]
Yes, this is exactly what is happening when using a remote. It also opens a closed cover.

Example of how one my covers is set up:
`       travelling_time_up: 23.0
        travelling_time_down: 21.1
        intermediate_position_up: 67
        intermediate_position_down: 28
` 
when cover is in position 0 and I double tap "down" on my remote it goes to position 28
when cover is in position 100 and I double tap "down" on my remote it goes to position 28
when cover is in position 28 and I double tap "down" on my remote it moves down a little bit before it goes up to position 28 again (it already starts going down after the first tab before it receives the second tab and therefore knows "oh intermediate position is wanted")

For sure same applies to the upper intermediate position.

From home assistant it does for sure at the moment not work like this, because the command sent to the cover depends on the current position where home assistant thinks the cover is. And also the interpretation of the commands in HASS sent by the remote is bound to the rules, so it comes to differences in the position shown in HASS and the actual position of the cover. (e.g. when cover is closed and then from the remote its moved to "intermediate_position_down" via double tap, HASS thinks its still closed, while actually its in Position 28)
And that is my problem...

**Comment by RainerStaude** [comment]
To be honest I don't use intermediate positions . Therefore I was not fully aware of these details. Looks like my documentation is wrong at that point.
I will test this with my cover, but I assume it behaves the same.

If I got you right, your cover also always goes to the intermediate position when control it from HASS. Just the position shown in HASS might not be correct.

If this is the case, it is easy to change. The Becker integration anyway has to emulate the behavior of the Becker covers. Just need to adapt the emulation to the real behavior of the covers.

**Comment by RainerStaude** [comment]
please see latest release v0.3.2
