### ISSUE TITLE
Component breaks KNX core integration

### ISSUE THREAD

**Issue by farmio** [RainerStaude/hass-becker-component-plus-pybecker#21]
https://github.com/RainerStaude/hass-becker-component-plus-pybecker/blob/10b69bc76ca3365ceda94656673516192c70ba4a/manifest.json#L7

This replaces the xknx version required by the core KNX integration, rendering it unusable. 
Please don't pin-require outdated xknx versions in your component. 

See https://community.home-assistant.io/t/secureconfig-error-in-knx-integration/566793

**Comment by RainerStaude** [comment]
I thought the xknx version from manifest.json requirements (of Becker custom integration) will only be used for this integration. I was not aware it overwrites the xknx version used for HA core.

**Comment by farmio** [comment]
Great! Maybe see this post (and few following) for an alternative approach that would probably be more future proof: https://community.home-assistant.io/t/yet-another-time-controlled-cover-rflink/72759/111?u=farmio

**Comment by Mattes83** [comment]
Unfortunately the pinning was neccessary. In the current version TravelCalculator has no "_calculate_travel_time"

**Comment by farmio** [comment]
It was just renamed `https://github.com/XKNX/xknx/blob/f5b71ca55cb7609065563b219d705d7666075ec1/xknx/devices/travelcalculator.py#L159`

But I think it's still not a good idea to import a 16kLOC library for some side-show proportion calculations.

**Comment by RainerStaude** [comment]
Done 😄 
Hope this works now

**Comment by farmio** [comment]
Thank you very much! Users of KNX and your component will appreciate it 😃
