### ISSUE TITLE
Faulty position indication after update to 0.3.2

### ISSUE THREAD

**Issue by AppleFlapp** [RainerStaude/hass-becker-component-plus-pybecker#25]
Since the update two of my blinds show wrong value when opened.
When opening and fully openened one shows 89% open and tthe other 91% but they are fully opened.

Adding a second to the travelling_time_up didn't improve, it actually got worse because then both show 86% when fully opened.

I have to press stop followed by up to get the value on 100%.

`      kitchen:
        friendly_name: "Kitchen Cover"
        # Becker Centronic USB stick provides up to five units (1-5) with up to seven (1-7) channels
        # Unit 1 - Channel 1
        channel: "1"
        tilt_blind: off
        tilt_intermediate: off
        # The travel time for direction up is sufficient if travel time for up and down are equal
        travelling_time_up: 27       
        # Optional travel time for direction down
        travelling_time_down: 24
        # Optional intermediate positions for up and down
        # intermediate_position_up: 75
        # intermediate_position_down: 25
        # Disable intermediate position when not used
        intermediate_position: off
      bedroom_1:
        friendly_name: "Master Bedroom Cover"
        # Unit 1 - Channel 2
        channel: "2"
        tilt_blind: off
        tilt_intermediate: off
        travelling_time_up: 16
        travelling_time_down: 14.5
        intermediate_position: off

More info:
The kitchen cover also becomes some kind of unresponsive. After closing it doesn't accept up although the up button is available. Pressing stop and down a few times makes it respond again to open.
But then the counter gets stuck on 89% and only after pressing stop it becomes 100%.

Already deleted the db file and restarted HA but no improvements yet.

Only strange behaviour on two of the five covers.

Also did update to  2023.5.2  this morning way before covers were opened.

**Comment by AppleFlapp** [comment]
Back to v0.3.0 and everything seems to be back to normal, for now.

**Comment by RainerStaude** [comment]
v0.3.3 fixes your issue
