### ISSUE TITLE
Support for multiple remotes and groups

### ISSUE THREAD

**Issue by marcschumacher** [RainerStaude/hass-becker-component-plus-pybecker#31]
It would be good to have support for multiple remotes being used with the integration or at least groups. When I not explicitly select a particular cover with the remote, but a group, the channel, which is steering multiple covers, is different, in my case `F`. Furthermore, I would think that having multiple remotes for the covers would result in a similar problem. Can you fix this?

**Comment by RainerStaude** [comment]
This is supported. When you add 
remote_id: "12345:2" 
then "12345:F" is automatically added.

**Comment by RainerStaude** [comment]
Is this working for you?
If you enable debug logs, you can verify the codes are received and verify the reaction of the covers in Home Assistant.
