### ISSUE TITLE
Centronic Plus Availability

### ISSUE THREAD

**Issue by rokl-dev** [RainerStaude/hass-becker-component-plus-pybecker#34]
Dear RainerStaude,

do you have any information on CentronicPlus availability? From what I've researched, there is no feedback yet on any implemented CentronicPlus shutter. I am only aware that the CentronicPlus stick is not working.

Since CentronicPlus is also implemented in Homee, do you see any chance that it will be implemented in the near future in HA by someone?

I am asking because we are currently installing new shutters and the technician highly recommends the CentronicPlus version with the CC41 base. He argues that, since it is working with so many systems (Google, Alexa, Fritzbox, Homee, etc) it should work wit HA as well... only, I doubt it and would prefer not having two bases standing around. Though, communication via Fritzbox would be an option. Also, I am not afraid of putting some programming work into it.

Alternatively, we can order Centronic shutters, but the technician expects communication issues (do you have any experience regarding range?) and we also tend to rather use the newer models.

Thanks in advance, Robert

**Comment by RainerStaude** [comment]
Hi Robert,

you can control Centronic Plus shutters with standard remotes. The Becker USB Stick with HA should work as well, as this acts like a standard remote. And it will receive the commands from your master remote as well.
BUT it will not make use of the "plus" features like mesh and extended range. Dependent on your house size it might be worth to try. 
Using an CC41 with an CentronicPlus Stick makes use of the new Features. 
The easiest way to integrate the CC41 into HA might be through REST API. But I have not seen an official documentation about this.
Please note that the HA Becker Integration is not officially supported whereas e.g. Homee seems to be officially supported.

Rainer

**Comment by anthudz19** [comment]
Becker Centronic Plus motors are backward compatible with Centronic Remotes. You can use the Centronic stick with Centronic Plus motors but will not have the bidirectional features. You can also use the Becker supplied Centronic Plus remotes and the motors will still create their own mesh radio network for greater radio range when using a Centronic Plus remote.  This mesh network will not be used when using the Centronic stick with HA.

**Comment by DominikStarke** [comment]
> The easiest way to integrate the CC41 into HA might be through REST API. But I have not seen an official documentation about this.

We can indeed call the CentralControls API. Here's an integration which does that:
https://github.com/DominikStarke/becker_centralcontrol_has

**Comment by RainerStaude** [comment]
Closed with integration from @DominikStarke
