### ISSUE TITLE
Thank you for your improvements

### ISSUE THREAD

**Issue by nicolasberthel** [RainerStaude/hass-becker-component-plus-pybecker#4]
Sorry to contact you via issues :D 
I tested your integration and it looks like a good improvements, once you are completely ready I can remove mine and forward to yours, it will reduce confusion for users.
I tried several time to push the integration to ha official integrations, I passed all the quality gates but it was rejected because it does not have a config flow. I created one (I can share it) but again it was rejected because it was not complete enough. I'm not a Python developer so sometime it's not so easy for me, maybe it's easier for you ;)
Looks like you want to push the integration to hass, which would be as well already a good improvement as well.
If you need (and if I can), do not hesitate to ask for help.
Regards
Nicolas

**Comment by RainerStaude** [comment]
@nicolasberthel, you are right, I would also prefer to have only 1 integration. I don't care whether this is "yours" or "mine". I would also prefer to put Becker naively into Home Assistant. It seems you already know what steps to perform for a official integration. I'm not a python developer as well, but I think the config flow should be feasible. I will contact you by mail.
