### ISSUE TITLE
HASS reports use of depricated hass.helpers.dispatcher

### ISSUE THREAD

**Issue by f69m** [RainerStaude/hass-becker-component-plus-pybecker#43]
Hello, in my logs I found the following message:

Detected that custom integration 'becker' accesses hass.helpers.dispatcher. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from dispatcher directly at custom_components/becker/cover.py, line 253: receive = self.hass.helpers.dispatcher.async_dispatcher_connect(, please report it to the author of the 'becker' custom integration

**Comment by RainerStaude** [comment]
I know. I will fix this in the next revision before November 😉

**Comment by RainerStaude** [comment]
closed with release [v0.3.5](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/tree/v0.3.5)
