### ISSUE TITLE
Works perfectly with Centronic USB dongle 4035 000 041 0

### ISSUE THREAD

**Issue by jandusek4** [RainerStaude/hass-becker-component-plus-pybecker#47]
![20240922_131613](https://github.com/user-attachments/assets/59b9d8c4-fe55-4b7a-ba6d-289df11ccc9d)

**Comment by RainerStaude** [comment]
closed with release [v0.3.5](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/tree/v0.3.5)
