### ISSUE TITLE
Cannot add repository to HA

### ISSUE THREAD

**Issue by crispyoz** [RainerStaude/hass-becker-component-plus-pybecker#53]
I'm trying to add the repository to my HA v 2024.11.2

Settings->Add-on Store->Add Repository

But it complains:

![image](https://github.com/user-attachments/assets/bdc661e0-6c3f-4c49-86b4-7cafe72a9f47)

Perhaps I misunderstood, I'm a complete newbie with HA.

**Comment by RainerStaude** [comment]
You need to install HACS in order to install this repository via [HACS](https://hacs.xyz/)
OR
download the repository and copy the content to config\custom_components\becker
