### ISSUE TITLE
Support for CentronicPLUS?

### ISSUE THREAD

**Issue by DerBorzi** [RainerStaude/hass-becker-component-plus-pybecker#58]
Hi Rainer,
is it possible to use a CentronicPLUS USB-Stick?
MfG
Andreas

**Comment by RainerStaude** [comment]
Hi Andreas,
Unfortunately this is not supported.
See [issue 34](https://github.com/RainerStaude/hass-becker-component-plus-pybecker/issues/34).
This is only supported through Becker Central Control.
