### ISSUE TITLE
Not working with Roto roof shutters

### ISSUE THREAD

**Issue by Flink** [RainerStaude/hass-becker-component-plus-pybecker#6]
Hi!

I basically have the exact same problem than the one described here: https://github.com/ole1986/centronic-py/issues/24
If I try to call the service `becker.pair` twice though, nothing happens the second time :confused: 
I’m using HAOS so I don’t have access to python when ssh’ing into the Core container. Any idea on how to make it work with your custom integration? (which seems very nice otherwise!)

**Comment by RainerStaude** [comment]
I will look into this later this week. It should not be a big deal.

**Comment by RainerStaude** [comment]
Could you try if the changes in the develop branch work for you:
https://github.com/RainerStaude/hass-becker-component-plus-pybecker/tree/develop

**Comment by Flink** [comment]
Just tried and it’s working perfectly! Thanks a lot :slightly_smiling_face:

**Comment by RainerStaude** [comment]
Great 😃
