### ISSUE TITLE
Question about manual/automatic mode

### ISSUE THREAD

**Issue by hstridh** [RainerStaude/hass-becker-component-plus-pybecker#7]
Hi,

I have covers with Becker engine and Becker sun/wind control. On my remote I have the possibility to put them in manual mode or automatic mode (sun/wind control is controlling).
I think the sun/wind control is good except the days when it is partly cloudy, then the covers go in and out a lot during the day.
I would like to set manual mode on my covers based on some conditions (weather etc).

Can I use the usb stick together with this component to put them in manual/automatic mode?

**Comment by RainerStaude** [comment]
Unfortunately this is not supported.
I even do not know if this is possible with the usb stick. 
I'm curious if this is possible. I also have a cover and a remote which could support automatic mode, but I currently have no sun/wind sensor.
I will dig into it and let you know.

**Comment by RainerStaude** [comment]
I asked her for some ideas https://github.com/ole1986/centronic-py/discussions/30#
I think it could be possible to control automatic/manual mode by usb stick. But it gets difficult if your remote has a different setting than your stick/home assistant. It seems like each new command repeats the mode. If you send alternating commands form your remote with one setting and home assistant with a different setting you would change modes each time you send a command from a different source.

What do you think?

Have you already bought the usb stick?

**Comment by hstridh** [comment]
Hi and thanks for the investigation,

It think it sounds interesting. If I would use the stick to control the manual/automatic mode I would barely use the remote anymore I think.
No, I haven't bought the usb stick yet.

**Comment by RainerStaude** [comment]
Do you already use Home Assistant?
Which solar/wind sensor and remote are you using?
