### ISSUE TITLE
Working on Synology DSM7

### ISSUE THREAD

**Issue by BOTIBO67** [RainerStaude/hass-becker-component-plus-pybecker#8]
Hello,
Is this solution with USB stick possible on HA installed on a NAS Synology with DSM 7? As this version of DSM is not USB friendly.
What is the driver used for this stick.
Thank you

**Comment by tossbek** [comment]
Hello, 
I am running Home Assistant with becker on DSM 7.1 as VM in Virtual Machine Manager (ova image). Works perfect. 
FYI: My synology has 6 GB RAM to run the VM and other apps.
Best Regards

**Comment by BOTIBO67** [comment]
Thank you very much for your Feedback.
